-- Module 1 first-pass consensus inserts generated from modules/Module_1B_TRACKER.md
-- Consensus_Observation rows are generated by scripts/export_module1_full_sql.py.
BEGIN;

INSERT INTO Consensus (
  consensus_statement, topic, version, agreement_level,
  num_supporting_papers, num_contradicting_papers, notes
) VALUES (
  'Chronic SCI lesion architecture is a multicompartment structure, not a single scar. The core evidence supports separately queryable fibrotic or ECM-rich matrix, astrocytic border, immune/myeloid containment zone, spared or reactive neural tissue, altered white matter, and cystic or repaired-tissue cavities when present.',
  'M1B-T001: Core lesion architecture',
  1,
  'moderate',
  NULL,
  NULL,
  '{"boundary_or_contradiction_handling": "Compartment definitions vary by model, time point, assay resolution, and whether lesions are contusive, hemisection, cavitary, or scaffold-repaired; do not collapse all scar biology into one field.", "boundary_tracker_ids": [], "claim_tracker_ids": ["M1B-C019", "M1B-C020", "M1B-C021", "M1B-C022", "M1B-C023", "M1B-C024"], "consensus_draft_id": "M1B-S001", "materialization_note": "Consensus-only compatibility export; full materialization with Consensus_Observation rows is generated by scripts/export_module1_full_sql.py.", "observation_tracker_ids": ["M1B-O037", "M1B-O038", "M1B-O039", "M1B-O040", "M1B-O041", "M1B-O042", "M1B-O043", "M1B-O044", "M1B-O045", "M1B-O046"], "source_agreement_label": "moderate", "source_tracker": "modules/Module_1B_TRACKER.md", "supporting_evidence_scope": "Supported by spatial transcriptomics and scar-matrix full-text evidence, with lower-confidence abstract/source-page support for chronic zone architecture and single-cell lesion ecology; observations M1B-O037-M1B-O046; claims M1B-C019-M1B-C024.", "topic_id": "M1B-T001"}'
);

INSERT INTO Consensus (
  consensus_statement, topic, version, agreement_level,
  num_supporting_papers, num_contradicting_papers, notes
) VALUES (
  'SCI fibrotic scarring arises from perivascular and meningeal-associated stromal lineages, but lineage assignment depends on marker system, Cre driver, injury geometry, dural disruption, and endpoint. The consensus is modulation, not ablation: partial attenuation can support repair in some models, whereas loss of closure-producing stroma can be harmful.',
  'M1B-T002: Fibrotic scar cellular origins',
  1,
  'moderate',
  NULL,
  NULL,
  '{"boundary_or_contradiction_handling": "M1B-X002 resolves apparent pericyte-versus-fibroblast conflicts as marker/system dependent; store marker, lineage driver, injury model, and dural status with each claim.", "boundary_tracker_ids": ["M1B-X002"], "claim_tracker_ids": ["M1B-C006", "M1B-C007", "M1B-C008", "M1B-C009", "M1B-C010", "M1B-C011", "M1B-C012"], "consensus_draft_id": "M1B-S002", "materialization_note": "Consensus-only compatibility export; full materialization with Consensus_Observation rows is generated by scripts/export_module1_full_sql.py.", "observation_tracker_ids": ["M1B-O012", "M1B-O013", "M1B-O014", "M1B-O015", "M1B-O016", "M1B-O017", "M1B-O018", "M1B-O019", "M1B-O020", "M1B-O021", "M1B-O022", "M1B-O023", "M1B-O024", "M1B-O025", "M1B-O026"], "source_agreement_label": "moderate", "source_tracker": "modules/Module_1B_TRACKER.md", "supporting_evidence_scope": "Supported by three full-text lineage/function studies; observations M1B-O012-M1B-O026; claims M1B-C006-M1B-C012.", "topic_id": "M1B-T002"}'
);

INSERT INTO Consensus (
  consensus_statement, topic, version, agreement_level,
  num_supporting_papers, num_contradicting_papers, notes
) VALUES (
  'Astrocytic scar borders are active wound-repair and containment structures with separable programs for formation, maintenance, recruitment, and morphology. Established scar-forming astrocytes may resist direct reversal, while border recruitment and organization remain intervention-sensitive in vivo.',
  'M1B-T003: Astrocytic border and wound-repair state',
  1,
  'moderate',
  NULL,
  NULL,
  '{"boundary_or_contradiction_handling": "M1B-X003 distinguishes established astrocyte-state reversal from border recruitment/organization. Source-page studies should remain medium confidence until full-text upgrades.", "boundary_tracker_ids": ["M1B-X003"], "claim_tracker_ids": ["M1B-C013", "M1B-C014", "M1B-C015", "M1B-C016", "M1B-C017", "M1B-C018"], "consensus_draft_id": "M1B-S003", "materialization_note": "Consensus-only compatibility export; full materialization with Consensus_Observation rows is generated by scripts/export_module1_full_sql.py.", "observation_tracker_ids": ["M1B-O027", "M1B-O028", "M1B-O029", "M1B-O030", "M1B-O031", "M1B-O032", "M1B-O033", "M1B-O034", "M1B-O035", "M1B-O036"], "source_agreement_label": "moderate", "source_tracker": "modules/Module_1B_TRACKER.md", "supporting_evidence_scope": "Strongest support comes from Tamaru 2023 full text, with source-page support from immune-corralling, Ryk, and wound-repair astrocyte studies; observations M1B-O027-M1B-O036; claims M1B-C013-M1B-C018.", "topic_id": "M1B-T003"}'
);

INSERT INTO Consensus (
  consensus_statement, topic, version, agreement_level,
  num_supporting_papers, num_contradicting_papers, notes
) VALUES (
  'Chronic SCI changes lesion mechanics, but stiffness direction is model- and method-dependent. No universal chronic-scar stiffness claim should be encoded without species, injury model, time point, tissue preparation, AFM method, and lesion subregion.',
  'M1B-T004: Chronic lesion biomechanics',
  1,
  'emerging',
  NULL,
  NULL,
  '{"boundary_or_contradiction_handling": "M1B-X001 is the central synthesis: rat hemisection scar softening and mouse contusion lesion stiffening are both admissible under different model/method conditions.", "boundary_tracker_ids": ["M1B-X001"], "claim_tracker_ids": ["M1B-C001", "M1B-C002", "M1B-C003", "M1B-C004", "M1B-C005"], "consensus_draft_id": "M1B-S004", "materialization_note": "Consensus-only compatibility export; full materialization with Consensus_Observation rows is generated by scripts/export_module1_full_sql.py.", "observation_tracker_ids": ["M1B-O001", "M1B-O002", "M1B-O003", "M1B-O004", "M1B-O005", "M1B-O006", "M1B-O007", "M1B-O008", "M1B-O009", "M1B-O010", "M1B-O011"], "source_agreement_label": "emerging / boundary-specific", "source_tracker": "modules/Module_1B_TRACKER.md", "supporting_evidence_scope": "Supported by two full-text mechanics studies with directly conflicting directionality; observations M1B-O001-M1B-O011; claims M1B-C001-M1B-C005.", "topic_id": "M1B-T004"}'
);

INSERT INTO Consensus (
  consensus_statement, topic, version, agreement_level,
  num_supporting_papers, num_contradicting_papers, notes
) VALUES (
  'Chronic scar resection divides into distinct intervention classes: tissue removal alone and resection followed by cavity or gap reconstruction. Resection alone is not consensus-reparative and may be harmful in contusion models, whereas scaffold or cell filling is a recurring but model- and endpoint-dependent reconstruction strategy.',
  'M1B-T005: Cavitary lesions, scar resection, and scaffold filling',
  1,
  'moderate',
  NULL,
  NULL,
  '{"boundary_or_contradiction_handling": "M1B-X004 resolves the apparent conflict by distinguishing tissue removal from reconstruction after resection; efficacy claims should not be generalized beyond feasibility/safety or specific animal endpoints.", "boundary_tracker_ids": ["M1B-X004"], "claim_tracker_ids": ["M1B-C030", "M1B-C031", "M1B-C032", "M1B-C033", "M1B-C034"], "consensus_draft_id": "M1B-S005", "materialization_note": "Consensus-only compatibility export; full materialization with Consensus_Observation rows is generated by scripts/export_module1_full_sql.py.", "observation_tracker_ids": ["M1B-O056", "M1B-O057", "M1B-O058", "M1B-O059", "M1B-O060", "M1B-O061", "M1B-O062"], "source_agreement_label": "moderate", "source_tracker": "modules/Module_1B_TRACKER.md", "supporting_evidence_scope": "Supported by two full-text resection/human scaffold studies plus abstract/source-page scaffold support; observations M1B-O056-M1B-O062; claims M1B-C030-M1B-C034.", "topic_id": "M1B-T005"}'
);

INSERT INTO Consensus (
  consensus_statement, topic, version, agreement_level,
  num_supporting_papers, num_contradicting_papers, notes
) VALUES (
  'Spared and lesion-remote white matter is an active recovery-linked compartment rather than normal residual tissue. It can carry chronic degeneration, repair-associated glial and immune remodeling, MRI-visible tract changes, debris and lipid-handling programs, and behavioral associations.',
  'M1B-T006: Spared and remote white matter',
  1,
  'moderate',
  NULL,
  NULL,
  '{"boundary_or_contradiction_handling": "Boundary conditions include tract, distance from lesion, injury severity, post-mortem versus in vivo imaging, and exact MRI/histology metric. Lower-access white matter papers should not carry high-confidence numeric claims yet.", "boundary_tracker_ids": [], "claim_tracker_ids": ["M1B-C025", "M1B-C026", "M1B-C027", "M1B-C028", "M1B-C029"], "consensus_draft_id": "M1B-S006", "materialization_note": "Consensus-only compatibility export; full materialization with Consensus_Observation rows is generated by scripts/export_module1_full_sql.py.", "observation_tracker_ids": ["M1B-O047", "M1B-O048", "M1B-O049", "M1B-O050", "M1B-O051", "M1B-O052", "M1B-O053", "M1B-O054", "M1B-O055"], "source_agreement_label": "moderate", "source_tracker": "modules/Module_1B_TRACKER.md", "supporting_evidence_scope": "Strongest support comes from McCallum 2026 full text, with imaging and abstract support from Scholtes, Song, and Rosenberg; observations M1B-O047-M1B-O055; claims M1B-C025-M1B-C029.", "topic_id": "M1B-T006"}'
);

INSERT INTO Consensus (
  consensus_statement, topic, version, agreement_level,
  num_supporting_papers, num_contradicting_papers, notes
) VALUES (
  'Human chronic SCI lesion architecture is multi-scale and should retain separate fields for local lesion geometry and tissue bridges, focal cystic atrophy, retained adjacent parenchyma, vascular territory and remote infarct-like pathology, scar-marker composition, segmental motoneuron/root pathology, remyelination status, perilesional DTI abnormalities, and remote motor-system degeneration.',
  'M1B-T007: Human chronic pathology and imaging geometry',
  1,
  'strong',
  NULL,
  NULL,
  '{"boundary_or_contradiction_handling": "M1B-X005 and M1B-X007 separate local lesion stability/adjacent mass preservation from remote degeneration, vascular infarct-like lesions, and syrinx-associated atrophy.", "boundary_tracker_ids": ["M1B-X005", "M1B-X007"], "claim_tracker_ids": ["M1B-C035", "M1B-C036", "M1B-C037", "M1B-C038", "M1B-C039", "M1B-C040", "M1B-C047", "M1B-C048", "M1B-C049", "M1B-C050"], "consensus_draft_id": "M1B-S007", "materialization_note": "Consensus-only compatibility export; full materialization with Consensus_Observation rows is generated by scripts/export_module1_full_sql.py.", "observation_tracker_ids": ["M1B-O063", "M1B-O064", "M1B-O065", "M1B-O066", "M1B-O067", "M1B-O068", "M1B-O069", "M1B-O070", "M1B-O080", "M1B-O081", "M1B-O082", "M1B-O083", "M1B-O084"], "source_agreement_label": "strong first-pass", "source_tracker": "modules/Module_1B_TRACKER.md", "supporting_evidence_scope": "Supported by five full-text human studies plus source-page pediatric DTI support; observations M1B-O063-M1B-O070 and M1B-O080-M1B-O084; claims M1B-C035-M1B-C040 and M1B-C047-M1B-C050.", "topic_id": "M1B-T007"}'
);

INSERT INTO Consensus (
  consensus_statement, topic, version, agreement_level,
  num_supporting_papers, num_contradicting_papers, notes
) VALUES (
  'Immune-glial lesion biology is phase-, cell-, function-, and endpoint-specific. Myeloid and glial responses can support corralling, compaction, containment, debris handling, and repair while also contributing to chronic neuroinflammatory pathology and remote effects.',
  'M1B-T008: Immune-glial containment and chronic inflammation',
  1,
  'moderate',
  NULL,
  NULL,
  '{"boundary_or_contradiction_handling": "M1B-X006 resolves the main tension as phase- and function-specific: protective early containment/debris roles can coexist with chronic inflammatory harm. Source-page mechanistic rows remain medium confidence.", "boundary_tracker_ids": ["M1B-X006"], "claim_tracker_ids": ["M1B-C041", "M1B-C042", "M1B-C043", "M1B-C044", "M1B-C045", "M1B-C046"], "consensus_draft_id": "M1B-S008", "materialization_note": "Consensus-only compatibility export; full materialization with Consensus_Observation rows is generated by scripts/export_module1_full_sql.py.", "observation_tracker_ids": ["M1B-O071", "M1B-O072", "M1B-O073", "M1B-O074", "M1B-O075", "M1B-O076", "M1B-O077", "M1B-O078", "M1B-O079"], "source_agreement_label": "moderate", "source_tracker": "modules/Module_1B_TRACKER.md", "supporting_evidence_scope": "Supported by Li 2020 full text plus source-page evidence from Zhou, Milich, and Gerber; observations M1B-O071-M1B-O079; claims M1B-C041-M1B-C046.", "topic_id": "M1B-T008"}'
);

COMMIT;
