#!/usr/bin/env python3
"""Integrate the completed priority-6 ECM/adhesion review batches."""

from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RELAY = ROOT / "work" / "module21_relay"
PAIR = RELAY / "module21a_all_pair_relay_coverage.tsv"
TF = RELAY / "module22a_ligand_tf_handoff.tsv"
REUSE = RELAY / "module21a_pathway_reuse_registry.tsv"
DETAIL = RELAY / "module21a_pair_relay_evidence_detail.tsv"
REVIEW = RELAY / "module21a_pair_relay_review_batches006_010.tsv"


def read(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def write(path: Path, fields: list[str], rows: list[dict[str, str]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, delimiter="\t", lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def add(rows, key, ids, locators, species, model, assay, relation, layer, branch, confidence, tf, status, note):
    rows.append({"key": key, "ids": ids, "locators": locators, "species": species, "model": model,
                 "assay": assay, "relation": relation, "layer": layer, "branch": branch,
                 "confidence": confidence, "tf": tf, "status": status, "note": note})


def main() -> None:
    pair_rows = read(PAIR)
    tf_rows = read(TF)
    reuse_rows = [r for r in read(REUSE) if r.get("validation_status") != "reviewed_batch006_010_candidate"]
    pair_by_review = {r["module20a_review_id"]: r for r in pair_rows}
    tf_by_pair = {r["pair_key"]: r for r in tf_rows}
    specs = []
    E = "https://pubmed.ncbi.nlm.nih.gov/"

    def ids(*nums): return [f"M20A-EXT-{n:04d}" for n in nums]

    # Collagen, agrin, contactin, Notch and early ECM.
    add(specs, "agrn_dag1", ids(147), E+"9417121/; https://pmc.ncbi.nlm.nih.gov/articles/PMC4760904/", "human, bovine and mouse", "cartilage/chondrocyte, muscle and kidney models", "binding/co-IP, gain/loss, DAG1 blockade and cartilage assays", "direct binding; receptor-proximal anchorage; function", "downstream_pathway_function", "AGRN-DAG1/LRP4 extracellular anchorage and chondrogenic branch", "medium", "SOX9 candidate", "reviewed_relay_candidate", "Glycosylation/complex context and non-SCI models limit reuse; cartilage target program belongs in Module22A.")
    add(specs, "app_dr6", ids(148), "https://pmc.ncbi.nlm.nih.gov/articles/PMC4403255/; https://pmc.ncbi.nlm.nih.gov/articles/PMC2677572/", "mouse", "HEK293 and neuronal injury systems", "2.2-A structure, expression, caspase and axon-degeneration assays", "direct structural interaction; receptor-complex function", "downstream_pathway_function", "APP E2-DR6 dimerization and axon-degeneration branch", "high", "", "reviewed_relay_candidate", "APP fragment/state and neuronal injury context are required.")
    add(specs, "chad_itga2b1", ids(149), "https://pmc.ncbi.nlm.nih.gov/articles/PMC3030393/; https://pmc.ncbi.nlm.nih.gov/articles/PMC2136766/", "human and bovine", "chondrocytes and fibroblasts", "adhesion-blocking peptide, alpha2beta1 affinity purification, ERK1/2", "receptor-proximal adhesion; function", "downstream_pathway_function", "CHAD-alpha2beta1 collagen-adhesion/MAPK branch", "medium", "", "reviewed_relay_candidate", "No purified full-length binary assay and no SCI model.")
    add(specs, "cntn1_notch1", ids(150), "https://pubmed.ncbi.nlm.nih.gov/14567914/", "mouse", "OLN-93 oligodendrocytes", "cell-contact, gamma-secretase, dominant-negative Notch and NICD assays", "trans/proximal interaction; receptor activation; function", "downstream_pathway_function", "CNTN1-NOTCH1-gamma-secretase/NICD axoglial branch", "high", "", "reviewed_relay_candidate", "No purified affinity assay; NICD is not itself a TF and MAG belongs in Module22A.")
    add(specs, "cntn1_notch2", ids(151), "https://pubmed.ncbi.nlm.nih.gov/14567914/", "mouse", "OLN-93 oligodendrocytes", "Notch-family dominant-negative/constitutive constructs and gamma-secretase assays", "receptor-proximal function", "downstream_pathway_function", "CNTN1-NOTCH2 noncanonical axoglial branch", "medium", "", "reviewed_relay_candidate", "Weaker pair isolation than Notch1; no purified binding assay.")
    add(specs, "col1a1_cd44", ids(152), "https://pmc.ncbi.nlm.nih.gov/articles/PMC13182600/", "rat", "T9-T10 contusion SCI and PC12 OGD/R", "co-IP/colocalization, COL1A1/CD44 manipulation, AG-490 and pJAK1/pSTAT3", "receptor-proximal association; function", "downstream_pathway_function", "COL1A1-CD44-JAK1/STAT3-autophagy SCI branch", "medium", "STAT3 candidate", "reviewed_relay_candidate", "No purified extracellular binding assay; AG-490 is nonspecific. The local mismatched PMID 42549511 is not used.")
    add(specs, "collagen1_gp6", ids(153,163), "https://pubmed.ncbi.nlm.nih.gov/18231936/", "human/ bovine collagen assays", "recombinant GPVI-Fc and platelets", "GPVI-Fc binding, suspension/immobilized collagen and platelet activation", "direct receptor-collagen binding; function", "downstream_pathway_function", "native collagen-I-GPVI/FcRgamma platelet branch", "medium", "", "reviewed_relay_candidate", "Evidence is for native collagen-I/fibril, not isolated COL1A1 or COL1A2.")
    add(specs, "collagen1_alpha10", ids(154,164), "https://pubmed.ncbi.nlm.nih.gov/11572855/; https://pubmed.ncbi.nlm.nih.gov/9685391/", "human and bovine", "purified alpha10 I-domain and cartilage", "Mg-dependent binding and collagen-affinity purification", "direct domain binding", "ligand_receptor_binding_or_activation", "native collagen-I/II-alpha10beta1 branch", "medium", "", "reviewed_binding_only", "Chain-isolated COL1A1/COL1A2 binding and SCI context were not established.")
    add(specs, "collagen1_alpha11", ids(155,165), "https://pubmed.ncbi.nlm.nih.gov/11518510/", "human and mouse engineered cells", "C2C12 alpha11beta1 transfectants", "collagen adhesion, gel contraction, focal contacts and migration", "direct/proximal collagen binding; function", "downstream_pathway_function", "native collagen-I-alpha11beta1 remodeling branch", "medium", "", "reviewed_relay_candidate", "Native collagen-I rather than isolated chains; engineered receptor context.")
    add(specs, "collagen1_alpha1", ids(156,166), "https://pubmed.ncbi.nlm.nih.gov/9699516/; https://pubmed.ncbi.nlm.nih.gov/10542255/; https://pubmed.ncbi.nlm.nih.gov/10986291/", "human and bovine", "recombinant integrin I-domains and cell assays", "SPR/ELISA, chimeric integrin and collagen subtype binding", "direct molecular/proximal collagen binding", "ligand_receptor_binding_or_activation", "native collagen-I-alpha1beta1 branch", "medium", "", "reviewed_binding_only", "Evidence is native collagen/recombinant domains, not isolated COL1A1/COL1A2." )
    add(specs, "collagen1_alpha2", ids(157,167), "https://pubmed.ncbi.nlm.nih.gov/10986291/; https://pubmed.ncbi.nlm.nih.gov/15145957/", "human and bovine", "recombinant alpha2 I-domain and native fibrils", "SPR/ELISA, fibril adhesion, spreading and contraction", "direct molecular binding; function", "downstream_pathway_function", "native collagen-I-alpha2beta1 branch", "high", "", "reviewed_relay_candidate", "High for native collagen-I; free COL1A1/COL1A2 chain not separately tested.")
    add(specs, "collagen1_alpha3_unresolved", ids(158), "https://pubmed.ncbi.nlm.nih.gov/7493650/; https://pmc.ncbi.nlm.nih.gov/articles/PMC556896/", "human/bovine", "chondrocyte and radioreceptor assays", "negative/non-supportive collagen-I binding assays", "negative/unresolved", "ligand_receptor_binding_or_activation", "no defensible COL1A1-alpha3beta1 branch", "low", "", "reviewed_unresolved", "Available assays are negative or non-supportive; do not reuse general collagen-integrin annotations.")
    add(specs, "collagen1_sdc1", ids(161,171), "https://pubmed.ncbi.nlm.nih.gov/7949658/; https://pmc.ncbi.nlm.nih.gov/articles/PMC2834805/", "mouse and human", "mammary epithelial cells and collagen-I adhesion models", "radiolabeled binding, SDC1 depletion/overexpression and alpha2beta1 blockade", "direct proteoglycan binding; receptor-proximal cooperation; function", "downstream_pathway_function", "native collagen-I-SDC1-HS/alpha2beta1 adhesion branch", "medium", "", "reviewed_relay_candidate", "HS chains and membrane presentation are required; not a canonical kinase receptor.")
    add(specs, "collagen1_avb8_unresolved", ids(170), "https://pubmed.ncbi.nlm.nih.gov/37909974/; https://doi.org/10.1016/S0021-9258(19)61963-0", "human", "oral squamous-cell carcinoma and recombinant alphaVbeta8", "migration/invasion, RAC1 pull-down and recombinant affinity comparison", "receptor-proximal function; contradictory binding", "ligand_receptor_binding_or_activation", "no defensible COL1A2-alphaVbeta8 direct branch", "low", "", "reviewed_unresolved", "Functional cancer-cell evidence conflicts with recombinant non-binding; do not promote direct collagen binding.")
    add(specs, "collagen2_gp6", ids(173), "https://pubmed.ncbi.nlm.nih.gov/18231936/", "bovine/human", "recombinant GPVI-Fc and platelets", "GPVI-Fc binding and platelet adhesion/activation", "direct receptor-collagen binding; function", "downstream_pathway_function", "native collagen-II-GPVI/FcRgamma platelet branch", "medium", "", "reviewed_relay_candidate", "Native collagen-II rather than isolated COL2A1.")
    add(specs, "collagen2_alpha10", ids(174), "https://pubmed.ncbi.nlm.nih.gov/9685391/", "bovine and human", "bovine chondrocyte alpha10 and cartilage", "collagen-II affinity purification and receptor characterization", "direct molecular/proximal binding; function", "downstream_pathway_function", "native collagen-II-alpha10beta1 cartilage branch", "high", "", "reviewed_relay_candidate", "Native collagen-II and chondrocyte context; chain alone not tested.")
    add(specs, "collagen2_alpha11_unresolved", ids(175), "https://pubmed.ncbi.nlm.nih.gov/11518510/", "human", "engineered alpha11beta1 cells", "collagen-I adhesion comparison", "family-level receptor evidence; exact collagen-II pair unresolved", "ligand_receptor_binding_or_activation", "no defensible COL2A1-alpha11beta1 branch", "low", "", "reviewed_unresolved", "Do not promote collagen-I evidence to exact collagen-II binding.")
    add(specs, "collagen2_alpha1", ids(176), "https://pubmed.ncbi.nlm.nih.gov/7493650/; https://pubmed.ncbi.nlm.nih.gov/10772239/", "human and bovine", "chondrocytes and collagen-II affinity assays", "affinity chromatography, adhesion and beta1 blocking", "direct molecular/proximal binding; function", "downstream_pathway_function", "native collagen-II-alpha1beta1 cartilage branch", "high", "", "reviewed_relay_candidate", "Native collagen-II rather than free COL2A1.")
    add(specs, "collagen2_alpha2", ids(177), "https://pubmed.ncbi.nlm.nih.gov/7493650/; https://pubmed.ncbi.nlm.nih.gov/7688313/", "human and bovine", "fetal cartilage and chondrocytes", "affinity chromatography, beta1/alpha2 blocking and adhesion", "direct molecular/proximal binding; function", "downstream_pathway_function", "native collagen-II-alpha2beta1 cartilage branch", "high", "", "reviewed_relay_candidate", "Native fibril/heterotrimer and receptor presentation required.")

    # Collagen IV/VI, COMP, Notch, DMP1, EPGN, CD23 and FN.
    add(specs, "collagen4_cd44_unresolved", ids(182), "https://pubmed.ncbi.nlm.nih.gov/?term=COL4A1+CD44; https://pubmed.ncbi.nlm.nih.gov/7513665/", "none qualifying", "exact-pair search boundary", "exact-pair search; separate collagen-IV/CD44 observations", "unresolved", "ligand_receptor_binding_or_activation", "no defensible COL4A1-CD44 branch", "low", "", "reviewed_unresolved", "Do not transfer CD44-CEA or general collagen-IV adhesion.")
    add(specs, "collagen4_alpha1", ids(186,196), "https://pubmed.ncbi.nlm.nih.gov/8344274/; https://pubmed.ncbi.nlm.nih.gov/9575174/", "human and biochemical systems", "collagen-IV fragments, isolated alpha1beta1 and mesangial cells", "solid-phase binding, inhibition and adhesion blocking", "direct binding; function", "ligand_receptor_binding_or_activation", "native collagen-IV-alpha1beta1 adhesion branch", "medium", "", "reviewed_binding_only", "Native/type-IV collagen or CB3 fragment; isolated COL4A1 not tested.")
    add(specs, "collagen4_alpha2", ids(187), "https://pubmed.ncbi.nlm.nih.gov/8344274/; https://pubmed.ncbi.nlm.nih.gov/9575174/", "human and biochemical systems", "collagen-IV fragments and isolated alpha2beta1", "solid-phase binding, inhibition and adhesion blocking", "direct binding; function", "ligand_receptor_binding_or_activation", "native collagen-IV-alpha2beta1 adhesion branch", "medium", "", "reviewed_binding_only", "Chain-composition caveat; not isolated COL4A1.")
    add(specs, "collagen4_col4a3_alpha3", ids(208), "https://pubmed.ncbi.nlm.nih.gov/16731529/", "human", "COL4A3 NC1-domain tumor/endothelial cells", "binding, adhesion, integrin loss/comparison and anti-integrin perturbation", "direct domain binding; function", "downstream_pathway_function", "COL4A3 NC1-alpha3beta1 adhesion/angiogenesis branch", "medium", "", "reviewed_relay_candidate", "NC1 domain only, not intact alpha3alpha4alpha5 collagen IV.")
    add(specs, "collagen6_alpha1", ids(246,256,266), "https://pubmed.ncbi.nlm.nih.gov/8387021/", "human", "native collagen-VI, purified integrins and adhesion assays", "affinity chromatography, purified-integrin binding and antibody inhibition", "direct type-level binding; function", "ligand_receptor_binding_or_activation", "native collagen-VI-alpha1beta1 adhesion branch", "medium", "", "reviewed_binding_only", "Native multichain collagen VI; COL6A1/COL6A2/COL6A3 chains not isolated.")
    add(specs, "collagen6_alpha2", ids(247,257,267), "https://pubmed.ncbi.nlm.nih.gov/8387021/", "human", "native collagen-VI, purified integrins and adhesion assays", "affinity chromatography, purified-integrin binding and antibody inhibition", "direct type-level binding; function", "ligand_receptor_binding_or_activation", "native collagen-VI-alpha2beta1 adhesion branch", "medium", "", "reviewed_binding_only", "Native multichain collagen VI; isolated chains not tested.")
    add(specs, "comp_cd36", ids(322), "https://pmc.ncbi.nlm.nih.gov/articles/PMC6146743/", "human and mouse", "HCC, LX2 and orthotopic tumors", "recombinant COMP, CD36 knockdown, pERK/pAKT and invasion assays", "receptor-dependent function", "downstream_pathway_function", "COMP-CD36-MEK/ERK and PI3K/AKT-EMT branch", "medium", "", "reviewed_relay_candidate", "Functional receptor dependence, not purified direct binding; tumor/fibrosis context.")
    add(specs, "comp_cd47", ids(323), "https://pmc.ncbi.nlm.nih.gov/articles/PMC3150962/", "mouse and human", "ligament cells and fetal chondrocytes", "COMP-coated adhesion, peptide competition and CD47 blocking", "receptor-proximal function", "downstream_pathway_function", "COMP-CD47 cytoskeletal adhesion branch", "medium", "", "reviewed_relay_candidate", "Peptide/blocking evidence does not define a complete full-length interface.")
    add(specs, "comp_avb3", ids(325), "https://pmc.ncbi.nlm.nih.gov/articles/PMC3150962/", "mouse and human", "ligament/cartilage cells", "RGD competition and alphaVbeta3 blocking", "receptor-proximal function", "downstream_pathway_function", "COMP-RGD-alphaVbeta3 adhesion branch", "medium", "", "reviewed_relay_candidate", "Conformation-dependent; no purified reconstitution.")
    add(specs, "dll3_notch1", ids(331), "https://pubmed.ncbi.nlm.nih.gov/25856312/; https://pmc.ncbi.nlm.nih.gov/articles/PMC4391858/", "mouse", "cultured cells and somitogenesis", "co-IP, cis-inhibition, O-fucosylation mutants and genetics", "direct cis interaction; cis inhibition", "receptor_proximal_relay", "DLL3-NOTCH1 noncanonical cis branch", "medium", "", "reviewed_relay_candidate", "Do not create canonical DLL3 trans activation.")
    add(specs, "dll3_notch2", ids(332), "https://pmc.ncbi.nlm.nih.gov/articles/PMC8816931/", "mouse", "oocytes/follicles and fertility knockout", "co-IP, MIB2/Gm364 perturbation, gamma-secretase, NICD2 and AKT", "direct association; receptor activation; function", "downstream_pathway_function", "DLL3-NOTCH2-MIB2-NICD2-AKT branch", "medium", "", "reviewed_relay_candidate", "Specialized oocyte context; not generalized trans activation.")
    add(specs, "dll4_notch3", ids(335), "https://pubmed.ncbi.nlm.nih.gov/19208840/", "human", "T-ALL/colorectal cells and endothelial coculture", "DLL4 induction, coculture, neutralization and NOTCH3 silencing", "functional ligand-receptor activation", "downstream_pathway_function", "DLL4-NOTCH3 endothelial/tumor branch", "medium", "", "reviewed_relay_candidate", "Disease/coculture context; no purified binding.")
    add(specs, "dll4_notch4", ids(336), "https://pubmed.ncbi.nlm.nih.gov/12814948/", "human", "dermal microvascular endothelial cells", "coculture, activated Notch4 comparison and HES/HERP assays", "functional ligand-receptor activation", "downstream_pathway_function", "DLL4-NOTCH4 vascular specification branch", "medium", "", "reviewed_relay_candidate", "HES/HERP are response genes, not terminal TF activation.")
    add(specs, "dmp1_avb3", ids(337), "https://pmc.ncbi.nlm.nih.gov/articles/PMC3190986/", "human and mouse", "MSC, MC3T3-E1 and odontoblast-like cells", "adhesion, alphaVbeta3 blockade, co-IP, FAK/ERK/JNK and c-Jun assays", "receptor-proximal complex; function", "downstream_pathway_function", "DMP1-alphaVbeta3-FAK-ERK/JNK branch", "medium", "c-Jun", "reviewed_relay_candidate", "Phospho-c-Jun nuclear/transcriptional activation measured; target program belongs in Module22A.")
    add(specs, "epgn_egfr", ids(338), "https://pubmed.ncbi.nlm.nih.gov/15611079/; https://doi.org/10.1074/jbc.M006935200", "human and mouse", "engineered CHO/myeloid, HaCaT and tumor contexts", "recombinant EPGN, ligand displacement, EGFR phosphorylation and proliferation", "direct ligand-receptor assignment; function", "receptor_proximal_relay", "EPGN-EGFR-MAPK mitogenic branch", "high", "", "reviewed_relay_candidate", "Low-affinity/engineered and epithelial-tumor contexts; no SCI validation.")
    add(specs, "cd23_cr2", ids(339), "https://pmc.ncbi.nlm.nih.gov/articles/PMC2212946/", "human", "recombinant CD23 and CR2 extracellular domains", "NMR structure and chemical-shift mapping", "direct molecular binding", "ligand_receptor_binding_or_activation", "CD23-CR2 B-cell coreceptor branch", "high", "", "reviewed_binding_only", "Domain-level binding with no terminal transcriptional readout.")
    add(specs, "fn1_cd44", ids(340), "https://pubmed.ncbi.nlm.nih.gov/9145328/; https://pubmed.ncbi.nlm.nih.gov/16886606/", "human", "lymphoid and prostate cancer cells", "FN adhesion, CD44 antibodies and isoform manipulation", "receptor-proximal adhesion; function", "downstream_pathway_function", "FN1-CD44 adhesion/cytoskeletal branch", "medium", "", "reviewed_relay_candidate", "No purified binary binding; CD44 isoform/activation state required.")
    add(specs, "fn1_a2b3", ids(341), "https://pubmed.ncbi.nlm.nih.gov/15456495/", "human and mouse", "platelets", "FN adhesion, integrin blockade, FAK/PLCgamma2/Ca2+", "functional receptor-mediated adhesion", "downstream_pathway_function", "FN1-alphaIIbbeta3 platelet outside-in branch", "high", "", "reviewed_relay_candidate", "Platelet activation state and FN domain context are required.")
    add(specs, "fn1_a3b1", ids(342), "https://pubmed.ncbi.nlm.nih.gov/20382852/", "mouse", "fresh cardiomyocytes", "AFM adhesion/unbinding and alpha3/beta1 blocking", "cell adhesion; receptor-proximal mechanotransduction", "downstream_pathway_function", "FN1-alpha3beta1 cardiomyocyte mechanotransduction branch", "medium", "", "reviewed_relay_candidate", "Mechanical/cardiomyocyte context; no soluble receptor assay.")
    add(specs, "fn1_a4b1", ids(343), "https://pmc.ncbi.nlm.nih.gov/articles/PMC2115745/", "human", "peripheral T lymphocytes", "CS-1/IIICS adhesion, alpha4 blocking and fragment comparisons", "direct receptor-specific cell adhesion", "downstream_pathway_function", "FN1-CS1-alpha4beta1 leukocyte adhesion branch", "high", "", "reviewed_relay_candidate", "Alternative-spliced FN/lymphocyte context.")

    # FN, perlecan, IBSP and laminin 1/2/3.
    add(specs, "fn1_a4b7", ids(344), "https://pmc.ncbi.nlm.nih.gov/articles/PMC2289398/", "mouse and human", "TK-1 and activated T cells", "CS-1 adhesion, affinity chromatography and antibody inhibition", "direct adhesion; function", "downstream_pathway_function", "FN1-CS1-alpha4beta7 lymphocyte adhesion branch", "medium", "", "reviewed_relay_candidate", "PMA/lymphocyte context; mucosal homing is MAdCAM-1, not FN.")
    add(specs, "fn1_a5b1", ids(345), "https://pubmed.ncbi.nlm.nih.gov/7691819/; https://pmc.ncbi.nlm.nih.gov/articles/PMC212714/; https://pmc.ncbi.nlm.nih.gov/articles/PMC2120698/", "human and mouse", "CHO/GD25 rescue and FN matrix assays", "binding, beta1 rescue, adhesion and fibrillogenesis", "direct binding; receptor-proximal function", "downstream_pathway_function", "FN1-alpha5beta1-RGD-focal adhesion/FAK-Src-RhoA branch", "high", "", "reviewed_relay_candidate", "Matrix geometry and receptor activation state are essential.")
    add(specs, "fn1_a8b1", ids(346), "https://pubmed.ncbi.nlm.nih.gov/7559467/; https://pmc.ncbi.nlm.nih.gov/articles/PMC301202/", "human and chick", "alpha8 transfectants and fibroblasts", "FN/RGD binding, inhibition and neurite outgrowth", "direct binding; function", "downstream_pathway_function", "FN1-RGD-alpha8beta1 adhesion/neurite branch", "medium", "", "reviewed_relay_candidate", "Transfected/recombinant context only.")
    add(specs, "fn1_avb1", ids(347), "https://pmc.ncbi.nlm.nih.gov/articles/PMC2119613/", "human engineered cells", "CHO-B2 alphaV cells", "FN adhesion/spreading, affinity and matrix assembly", "direct binding; function", "downstream_pathway_function", "FN1-alphaVbeta1 adhesion branch", "medium", "", "reviewed_relay_candidate", "Engineered CHO context; FN fibrillogenesis/migration not supported for this pair.")
    add(specs, "fn1_avb3", ids(348), "https://pmc.ncbi.nlm.nih.gov/articles/PMC2116382/; https://pmc.ncbi.nlm.nih.gov/articles/PMC2173988/", "human and mouse", "reconstituted alphaVbeta3/K562/GD25 cells", "solid-phase binding, RGD inhibition, RhoA, focal contacts and fibrillogenesis", "direct binding; function", "downstream_pathway_function", "FN1-alphaVbeta3-RGD/RhoA focal adhesion branch", "medium-high", "", "reviewed_relay_candidate", "Alpha5beta1 cooperation and matrix context matter.")
    add(specs, "fn1_avb6", ids(349), "https://pubmed.ncbi.nlm.nih.gov/1532572/; https://pubmed.ncbi.nlm.nih.gov/9664040/", "human and mouse", "FG-2, beta6-CHO and keratinocytes", "affinity chromatography, adhesion/migration, PMA/HGF and PKC inhibition", "direct binding; function", "downstream_pathway_function", "FN1-RGD-alphaVbeta6-PKC adhesion/migration branch", "medium", "", "reviewed_relay_candidate", "Do not substitute latent-TGFbeta ligand evidence.")
    add(specs, "fn1_avb8_unresolved", ids(350), "https://pmc.ncbi.nlm.nih.gov/articles/PMC4882426/", "human recombinant", "alphaVbeta8 ligand panel", "native FN versus engineered RGDS-to-RGDL binding", "weak direct binding; unresolved native function", "ligand_receptor_binding_or_activation", "no defensible native FN1-alphaVbeta8 branch", "low", "", "reviewed_unresolved", "Strong binding required engineered motif; native physiological edge remains unresolved.")
    add(specs, "fn1_sdc1", ids(351), "https://pmc.ncbi.nlm.nih.gov/articles/PMC2120752/", "human/mouse heterologous", "Raji SDC1 cells", "immobilized FN adhesion, SDC1 blockade and cytoskeletal inhibitors", "receptor-proximal HS/core-protein function", "downstream_pathway_function", "FN1-SDC1-HS spreading branch", "medium", "", "reviewed_relay_candidate", "Not purified binary binding; HS and heterologous expression required.")
    add(specs, "hspg2_dag1", ids(352), "https://pubmed.ncbi.nlm.nih.gov/10022829/; https://pubmed.ncbi.nlm.nih.gov/16098969/; https://pubmed.ncbi.nlm.nih.gov/38198277/", "human and mouse", "perlecan/laminin domains, alpha-dystroglycan and hPSC cardiomyocytes", "glycosylation-dependent solid phase and trimolecular-complex assays", "direct domain binding; receptor-complex function", "downstream_pathway_function", "HSPG2-G-domain-DAG1 basement-membrane branch", "medium", "", "reviewed_relay_candidate", "Glycosylation/trimolecular context limits binary interpretation.")
    add(specs, "ibsp_avb3", ids(353), "https://pubmed.ncbi.nlm.nih.gov/10785511/", "human and chick", "HUVEC and chick CAM", "RGD-mutant, cyclic RGD and alphaVbeta3 blockade", "ligand-specific functional adhesion; function", "downstream_pathway_function", "IBSP-RGD-alphaVbeta3 angiogenesis branch", "medium", "", "reviewed_relay_candidate", "No purified receptor biochemistry.")
    add(specs, "ibsp_avb5", ids(354), "https://pmc.ncbi.nlm.nih.gov/articles/PMC11413474/", "human", "MDA-MB-231, PC-3 and NCI-H460", "BSP-coated adhesion, RGD competition and alphaVbeta3/5 blockade", "functional adhesion", "downstream_pathway_function", "IBSP-RGD-alphaVbeta5 cancer-cell adhesion branch", "medium", "", "reviewed_relay_candidate", "Cell-line-specific antibody effects; no purified binding.")
    add(specs, "lama1_cd44_unresolved", ids(356), "https://doi.org/10.1016/0960-7404(93)90015-Q", "human", "colorectal carcinoma lines", "CD44E blockade of laminin adhesion", "functional adhesion; unresolved binary binding", "ligand_receptor_binding_or_activation", "no defensible LAMA1-CD44 branch", "low", "", "reviewed_unresolved", "Older laminin nomenclature and antibody blockade do not establish intact LAMA1 binding.")
    add(specs, "lama1_dag1", ids(357), "https://pubmed.ncbi.nlm.nih.gov/8631999/; https://pmc.ncbi.nlm.nih.gov/articles/PMC2120507/", "rabbit and mouse", "skeletal muscle alpha-DAG and embryonic kidney", "binding, perturbation and morphogenesis assays", "direct binding; receptor-complex function", "downstream_pathway_function", "LAMA1/laminin-111-DAG1/DGC branch", "high", "", "reviewed_relay_candidate", "Glycosylated DAG1 and laminin isoform specificity required.")
    add(specs, "lama1_a2b1", ids(358), "https://pubmed.ncbi.nlm.nih.gov/7525287/", "mouse", "purified alpha2beta1 and laminin-1", "EDTA-sensitive binding, inhibition and SPR", "direct molecular binding", "ligand_receptor_binding_or_activation", "LAMA1-alpha2beta1 matrix adhesion branch", "medium", "", "reviewed_binding_only", "Purified receptor/tumor laminin context only.")
    add(specs, "lama1_a6b1", ids(360), "https://pubmed.ncbi.nlm.nih.gov/16413178/", "human recombinant", "purified laminin isoforms and alpha6beta1", "binding-specificity panel", "direct molecular binding", "ligand_receptor_binding_or_activation", "LAMA1-alpha6beta1 laminin-recognition branch", "medium", "", "reviewed_binding_only", "Broad alpha6beta1 receptor; isoform-defined reuse only.")
    add(specs, "lama1_a6b4_unresolved", ids(361), "https://pubmed.ncbi.nlm.nih.gov/1533398/; https://pubmed.ncbi.nlm.nih.gov/16413178/", "human", "colon carcinoma laminin-E8 adhesion", "E8 adhesion and alpha6beta4 blockade", "fragment-level adhesion; unresolved intact binding", "ligand_receptor_binding_or_activation", "no defensible intact LAMA1-alpha6beta4 branch", "low", "", "reviewed_unresolved", "E8/older laminin nomenclature does not establish intact LAMA1 specificity.")
    add(specs, "lama1_a7b1", ids(362), "https://pubmed.ncbi.nlm.nih.gov/16413178/", "human recombinant", "alpha7 splice variants and laminin panel", "binding-specificity assay", "direct molecular binding", "ligand_receptor_binding_or_activation", "LAMA1-alpha7beta1 splice-dependent adhesion branch", "medium", "", "reviewed_binding_only", "Alpha7 splice variant must be retained.")
    add(specs, "lama2_dag1", ids(366), "https://pubmed.ncbi.nlm.nih.gov/8349731/; https://pubmed.ncbi.nlm.nih.gov/7925941/; https://pubmed.ncbi.nlm.nih.gov/9727035/", "mouse and human", "muscle/peripheral nerve laminin-2/merosin", "binding, glycosylation, calcium/heparin and genetic/functional assays", "direct binding; receptor-complex function", "downstream_pathway_function", "LAMA2/laminin-211-DAG1/DGC muscle-nerve branch", "high", "", "reviewed_relay_candidate", "Glycosylated DAG1 and laminin-211/221 isoform specificity required.")
    add(specs, "lama2_a2b1", ids(367), "https://pubmed.ncbi.nlm.nih.gov/9361014/; https://pubmed.ncbi.nlm.nih.gov/16891133/", "human", "laminin-2/4 domain and A-431 cells", "short-arm binding, neurite outgrowth and adhesion/migration", "fragment-level binding; function", "downstream_pathway_function", "LAMA2-laminin-2/4-alpha2beta1 branch", "low", "", "reviewed_relay_candidate", "Fragment/broad laminin evidence, not clean intact trimer binding.")
    add(specs, "lama2_a6b1", ids(369), "https://pubmed.ncbi.nlm.nih.gov/16413178/; https://pmc.ncbi.nlm.nih.gov/articles/PMC3893357/", "human and mouse", "recombinant laminin and Schwann cells/DRG", "binding, alpha6 deletion, spreading and radial sorting", "direct binding; function", "downstream_pathway_function", "LAMA2/laminin-211-alpha6beta1 Schwann branch", "high", "", "reviewed_relay_candidate", "Alpha6 is broad-spectrum and alpha7 can compensate; tissue-specific reuse.")
    add(specs, "lama2_a6b4_unresolved", ids(370), "https://pubmed.ncbi.nlm.nih.gov/16891133/; https://pmc.ncbi.nlm.nih.gov/articles/PMC5479503/", "human, mouse and rat", "A-431 and Schwann-cell laminin-211 model", "adhesion/migration and whole-laminin Schwann signaling", "functional/proximal; unresolved receptor-isolated binding", "ligand_receptor_binding_or_activation", "no defensible intact LAMA2-alpha6beta4 branch", "low", "", "reviewed_unresolved", "Oct6/Egr2 were whole-model readouts, not alpha6beta4-specific activation.")
    add(specs, "lama2_a7b1", ids(371), "https://pubmed.ncbi.nlm.nih.gov/16413178/; https://pmc.ncbi.nlm.nih.gov/articles/PMC3893357/", "human and mouse", "alpha7 splice variants and Schwann cells", "binding, alpha7 deletion and radial sorting", "direct binding; function", "downstream_pathway_function", "LAMA2/laminin-211-alpha7beta1 Schwann branch", "high", "", "reviewed_relay_candidate", "Splice-variant and tissue dependence; alpha6 compensation possible.")
    add(specs, "lama3_a2b1", ids(376), "https://pubmed.ncbi.nlm.nih.gov/11171386/", "human", "keratinocytes", "TGFbeta1 migration, laminin-5 deposition and alpha2beta1 interaction", "domain/proximal binding; function", "downstream_pathway_function", "LAMA3/laminin-332-alpha2beta1 keratinocyte migration branch", "medium", "", "reviewed_relay_candidate", "Processed/unprocessed gamma2 and older laminin-5 nomenclature matter.")
    add(specs, "lama3_a3b1", ids(377), "https://pubmed.ncbi.nlm.nih.gov/16413178/; https://pmc.ncbi.nlm.nih.gov/articles/PMC2861493/; https://pubmed.ncbi.nlm.nih.gov/18045589/", "human", "recombinant mini-Lm332 and epithelial cells", "binding, truncation, attachment, spreading and migration", "direct binding; receptor-proximal function", "downstream_pathway_function", "LAMA3/laminin-332-alpha3beta1 focal-adhesion/migration branch", "high", "", "reviewed_relay_candidate", "Mini-laminin/gamma2 architecture must be retained.")
    add(specs, "lama3_a6b1", ids(378), "https://pubmed.ncbi.nlm.nih.gov/16413178/", "human recombinant", "alpha6beta1 and laminin panel", "binding-specificity assay", "direct molecular binding", "ligand_receptor_binding_or_activation", "LAMA3/laminin-332-alpha6beta1 adhesion branch", "medium", "", "reviewed_binding_only", "Broad alpha6beta1 specificity; recombinant/isoform-defined.")
    add(specs, "lamb3_a2b1", ids(421), "https://pubmed.ncbi.nlm.nih.gov/11171386/", "human", "keratinocytes and laminin-332 gamma2 short-arm", "alpha2beta1 adhesion, spreading and migration", "domain/proximal binding; function", "downstream_pathway_function", "LAMB3/laminin-332-alpha2beta1 branch", "medium", "", "reviewed_relay_candidate", "Evidence is intact LM332/short-arm context, not isolated LAMB3 binding.")
    add(specs, "lamb3_a3b1", ids(422), "https://pubmed.ncbi.nlm.nih.gov/16413178/; https://pubmed.ncbi.nlm.nih.gov/20347131/; https://pubmed.ncbi.nlm.nih.gov/18045589/", "human", "recombinant LM332 and epithelial cells", "binding, truncation, attachment, spreading and migration", "direct binding; receptor-proximal function", "downstream_pathway_function", "LAMB3/laminin-332-alpha3beta1 branch", "high", "", "reviewed_relay_candidate", "Intact LM332 and gamma2 architecture required; chain-alone attribution limited.")
    add(specs, "lamb3_a6b1", ids(423), "https://pubmed.ncbi.nlm.nih.gov/16413178/", "human recombinant", "alpha6beta1 and laminin panel", "binding-specificity assay", "direct molecular binding", "ligand_receptor_binding_or_activation", "LAMB3/laminin-332-alpha6beta1 branch", "medium", "", "reviewed_binding_only", "Broad alpha6beta1 specificity; intact LM332 context.")

    # Laminin 3/4/5, netrin, NCAM, reelin and thrombospondin.
    add(specs, "lama3_a6b4", ids(379,424), "https://pubmed.ncbi.nlm.nih.gov/16413178/; https://pmc.ncbi.nlm.nih.gov/articles/PMC2820731/; https://pmc.ncbi.nlm.nih.gov/articles/PMC2289398/", "human, mouse and recombinant", "laminin-332/LM332 epithelial and keratinocyte models", "integrin binding, adhesion, hemidesmosome organization and beta4-tail signaling", "direct binding; receptor-proximal function", "downstream_pathway_function", "LAMA3/LAMB3-laminin-332-alpha6beta4 hemidesmosome branch", "high", "NF-kB p65 candidate", "reviewed_relay_candidate", "Evidence is intact LM332, not isolated LAMA3/LAMB3; NF-kB p65 was measured in mouse keratinocytes on laminin-332 and belongs in Module22A.")
    add(specs, "lama4_a3b1", ids(386), "https://pubmed.ncbi.nlm.nih.gov/11278628/; https://pubmed.ncbi.nlm.nih.gov/16413178/", "human", "K562 alpha3beta1 and purified laminin-411", "adhesion/migration and recombinant laminin binding", "direct/functional adhesion", "downstream_pathway_function", "LAMA4/laminin-411-alpha3beta1 branch", "medium", "", "reviewed_relay_candidate", "Intact laminin isoform, not LAMA4 chain alone; no SCI model.")
    add(specs, "lama4_a6b1", ids(387), "https://pubmed.ncbi.nlm.nih.gov/11278628/; https://pmc.ncbi.nlm.nih.gov/articles/PMC3893357/", "human and mouse", "laminin-411 adhesion and Schwann alpha6 deletion", "adhesion, migration and binding", "direct/functional adhesion", "downstream_pathway_function", "LAMA4/laminin-411-alpha6beta1 branch", "medium", "", "reviewed_relay_candidate", "Human evidence stronger; mouse functional context.")
    add(specs, "lama4_a7b1", ids(389), "https://pubmed.ncbi.nlm.nih.gov/16413178/; https://pmc.ncbi.nlm.nih.gov/articles/PMC3893357/", "human and mouse", "recombinant alpha7 splice variants and Schwann cells", "binding and deletion/radial-sorting assays", "direct binding; function", "downstream_pathway_function", "LAMA4/laminin-411-alpha7beta1 branch", "low", "", "reviewed_relay_candidate", "Weak/splice-dependent; reuse only tested alpha7 variant and laminin-411.")
    add(specs, "lama5_cd44_unresolved", ids(392), "https://pubmed.ncbi.nlm.nih.gov/32621878/", "human", "laminin-332 gamma2 fragment", "CD44 recruitment assay", "different-ligand evidence; unresolved", "ligand_receptor_binding_or_activation", "no defensible LAMA5-CD44 branch", "low", "", "reviewed_unresolved", "CD44 evidence is for laminin-332 gamma2, not LAMA5.")
    add(specs, "lama5_dag1", ids(393), "https://pmc.ncbi.nlm.nih.gov/articles/PMC6737067/", "human", "hiPSC and glycosylated alpha-DAG", "overlay, ELISA, peptide mapping and adhesion", "direct proximal binding; function", "downstream_pathway_function", "LAMA5/laminin-511-DAG1 anchorage branch", "medium-low", "", "reviewed_relay_candidate", "Weak and E8/coiled-coil/glycosylation dependent.")
    add(specs, "lama5_a2b1_unresolved", ids(394), "https://pubmed.ncbi.nlm.nih.gov/11098055/; https://pubmed.ncbi.nlm.nih.gov/16413178/", "human recombinant", "laminin alpha5 domain and laminin panel", "cell-binding and recombinant receptor assays", "non-supportive/uncertain binding", "ligand_receptor_binding_or_activation", "no defensible LAMA5-alpha2beta1 branch", "low", "", "reviewed_unresolved", "Alpha5 domain evidence favors alpha3beta1; intact Lm511/521-alpha2beta1 not established.")
    add(specs, "lama5_a3b1", ids(395), "https://pubmed.ncbi.nlm.nih.gov/10671376/; https://pubmed.ncbi.nlm.nih.gov/16413178/", "human", "laminin-511/521 and alpha3beta1 transfectants", "adhesion and recombinant binding", "direct binding; function", "downstream_pathway_function", "LAMA5/laminin-511/521-alpha3beta1 branch", "high", "", "reviewed_relay_candidate", "Intact laminin isoform, not chain-alone.")
    add(specs, "lama5_a6b1", ids(396), "https://pmc.ncbi.nlm.nih.gov/articles/PMC5580876/; https://pmc.ncbi.nlm.nih.gov/articles/PMC4281560/", "human", "laminin-511/521 and breast cancer stem cells", "structural binding, alpha6Bbeta1 perturbation, nuclear TAZ, TEAD reporter and target genes", "direct binding; receptor-proximal function", "downstream_pathway_function", "LAMA5/laminin-511-alpha6Bbeta1-TAZ/TEAD branch", "high", "TAZ; TEAD candidates", "reviewed_relay_candidate", "Direct TAZ/TEAD activation is context-specific and belongs in Module22A; generic alpha6beta1/mouse SCI transfer is not justified.")
    add(specs, "lama5_a6b4", ids(397), "https://pubmed.ncbi.nlm.nih.gov/16413178/; https://pmc.ncbi.nlm.nih.gov/articles/PMC2820731/", "human recombinant", "laminin-511/521 and alpha6beta4", "binding and adhesion", "direct binding; receptor-proximal adhesion", "downstream_pathway_function", "LAMA5/laminin-511/521-alpha6beta4 branch", "medium-high", "", "reviewed_relay_candidate", "Do not transfer laminin-332 NF-kB evidence to this ligand isoform.")
    add(specs, "lama5_a7b1", ids(398), "https://pubmed.ncbi.nlm.nih.gov/16413178/; https://pmc.ncbi.nlm.nih.gov/articles/PMC2658076/", "human recombinant", "alpha7 splice variants and beta-chain laminin panel", "binding and splice/chain comparison", "direct binding", "ligand_receptor_binding_or_activation", "LAMA5/laminin-511/521-alpha7beta1 splice branch", "medium", "", "reviewed_binding_only", "Retain alpha7 splice variant and intact laminin context.")
    add(specs, "lamb1_dag1", ids(402,411), "https://pmc.ncbi.nlm.nih.gov/articles/PMC6737067/; https://pubmed.ncbi.nlm.nih.gov/31506597/", "human", "glycosylated DAG1 and laminin-511/521 E8", "overlay/ELISA/adhesion", "weak direct proximal binding", "ligand_receptor_binding_or_activation", "laminin-511/521-DAG1 binding branch", "low", "", "reviewed_binding_only", "Evidence is intact laminin/E8, not LAMB1/LAMB2 chain-isolated; weak and glycosylation-dependent.")
    add(specs, "lamb1_a2b1_unresolved", ids(403), "https://pubmed.ncbi.nlm.nih.gov/11098055/; https://pubmed.ncbi.nlm.nih.gov/16413178/", "human recombinant", "laminin alpha5 and integrin panel", "binding comparison", "non-supportive/uncertain binding", "ligand_receptor_binding_or_activation", "no defensible LAMB1-alpha2beta1 branch", "low", "", "reviewed_unresolved", "Do not infer from alpha2beta1 collagen biology.")
    add(specs, "lamb1_a3b1", ids(404), "https://pubmed.ncbi.nlm.nih.gov/10671376/; https://pubmed.ncbi.nlm.nih.gov/16413178/", "human", "laminin-511/521 and alpha3beta1", "adhesion and recombinant binding", "direct binding; function", "downstream_pathway_function", "LAMB1/laminin-511/521-alpha3beta1 branch", "medium", "", "reviewed_relay_candidate", "Stronger for intact laminin than chain-alone.")
    add(specs, "lamb1_a6b1", ids(405), "https://pubmed.ncbi.nlm.nih.gov/10671376/; https://pmc.ncbi.nlm.nih.gov/articles/PMC5580876/", "human", "laminin-511 and alpha6beta1", "binding/adhesion", "direct binding; function", "downstream_pathway_function", "LAMB1/laminin-511-alpha6beta1 branch", "high", "", "reviewed_relay_candidate", "Intact laminin context required.")
    add(specs, "lamb1_a6b4", ids(406), "https://pubmed.ncbi.nlm.nih.gov/10671376/; https://pubmed.ncbi.nlm.nih.gov/16413178/", "human", "laminin-511/521 and alpha6beta4", "binding/adhesion", "direct binding; receptor-proximal adhesion", "downstream_pathway_function", "LAMB1/laminin-511/521-alpha6beta4 branch", "medium-high", "", "reviewed_relay_candidate", "Beta4-tail signaling remains context-limited.")
    add(specs, "lamb1_a7b1", ids(407), "https://pubmed.ncbi.nlm.nih.gov/16413178/; https://pmc.ncbi.nlm.nih.gov/articles/PMC2658076/", "human recombinant", "alpha7 splice variants and laminin panel", "binding and splice/chain comparison", "direct binding", "ligand_receptor_binding_or_activation", "LAMB1/laminin-511/521-alpha7beta1 branch", "medium", "", "reviewed_binding_only", "Splice-specific and intact laminin evidence.")
    add(specs, "lamc1_dag1", ids(429), "https://pubmed.ncbi.nlm.nih.gov/8631999/; https://pubmed.ncbi.nlm.nih.gov/7790379/", "rabbit and mouse", "skeletal muscle/nerve laminin-DAG1 systems", "alpha-dystroglycan binding and glycosylation-dependent anchorage", "direct proximal binding", "ligand_receptor_binding_or_activation", "LAMC1/laminin-DAG1 basement-membrane branch", "medium", "", "reviewed_binding_only", "Contact maps to alpha-chain LG domains; gamma1-specific contact unresolved.")
    add(specs, "lamc1_a2b1", ids(430), "https://pubmed.ncbi.nlm.nih.gov/7525287/; https://pubmed.ncbi.nlm.nih.gov/16413178/", "human and mouse", "purified alpha2beta1 and laminin isoforms", "binding and endothelial adhesion", "direct/proximal binding", "ligand_receptor_binding_or_activation", "LAMC1/laminin-alpha2beta1 branch", "low", "", "reviewed_binding_only", "Whole laminin/alpha-chain evidence; gamma1-only attribution unresolved.")
    add(specs, "lamc1_a3b1", ids(431), "https://pubmed.ncbi.nlm.nih.gov/16413178/; https://pubmed.ncbi.nlm.nih.gov/10671376/", "human recombinant", "laminin-511/521 and alpha3beta1", "recombinant binding and basement-membrane adhesion", "direct/proximal binding; function", "downstream_pathway_function", "LAMC1/laminin-alpha3beta1 branch", "high", "", "reviewed_relay_candidate", "Intact laminin complex, not gamma1 chain alone.")
    add(specs, "lamc1_a6b1", ids(432), "https://pubmed.ncbi.nlm.nih.gov/16413178/; https://pubmed.ncbi.nlm.nih.gov/10671376/", "human recombinant", "laminin panel and alpha6beta1", "recombinant binding and adhesion", "direct/proximal binding; function", "downstream_pathway_function", "LAMC1/laminin-alpha6beta1 branch", "high", "", "reviewed_relay_candidate", "Whole laminin isoform context required.")
    add(specs, "lamc1_a6b4", ids(433), "https://pubmed.ncbi.nlm.nih.gov/16413178/; https://pubmed.ncbi.nlm.nih.gov/1533398/", "human recombinant", "laminin-511/521 and alpha6beta4", "binding and epithelial adhesion", "direct/proximal binding; function", "downstream_pathway_function", "LAMC1/laminin-alpha6beta4 hemidesmosome branch", "high", "", "reviewed_relay_candidate", "Gamma1 is a complex component, not isolated receptor-contact evidence.")
    add(specs, "lamc1_a7b1", ids(434), "https://pubmed.ncbi.nlm.nih.gov/16413178/", "human recombinant", "alpha7 splice variants and laminin panel", "binding-specificity assay", "direct molecular binding", "ligand_receptor_binding_or_activation", "LAMC1/laminin-alpha7beta1 branch", "high", "", "reviewed_binding_only", "Isoform/splice-specific intact-laminin evidence.")
    add(specs, "lamc2_a2b1", ids(439), "https://pubmed.ncbi.nlm.nih.gov/11171386/", "human", "neonatal keratinocytes", "TGFbeta1 migration, gamma2 short-arm localization and adhesion", "domain/proximal binding; function", "downstream_pathway_function", "LAMC2/laminin-332-alpha2beta1 keratinocyte branch", "high", "", "reviewed_relay_candidate", "Strongest for unprocessed LM332/gamma2 short arm; processed state matters.")
    add(specs, "lamc2_a3b1", ids(440), "https://pubmed.ncbi.nlm.nih.gov/16413178/; https://pubmed.ncbi.nlm.nih.gov/20347131/; https://pubmed.ncbi.nlm.nih.gov/18045589/", "human", "intact LM332 and epithelial cells", "binding, gamma2 deletion, attachment and migration", "direct/proximal binding; function", "downstream_pathway_function", "LAMC2/laminin-332-alpha3beta1 branch", "high", "", "reviewed_relay_candidate", "Gamma2 deletion affects complex binding; peptide alone does not establish direct gamma2 contact.")
    add(specs, "lamc2_a6b1", ids(441), "https://pubmed.ncbi.nlm.nih.gov/16413178/", "human recombinant", "LM332 and alpha6beta1", "recombinant laminin binding panel", "direct/proximal binding", "downstream_pathway_function", "LAMC2/laminin-332-alpha6beta1 branch", "high", "", "reviewed_relay_candidate", "Intact LM332/receptor-state context required.")
    add(specs, "lamc2_a6b4", ids(442), "https://pubmed.ncbi.nlm.nih.gov/16413178/; https://pmc.ncbi.nlm.nih.gov/articles/PMC2820731/", "human", "LM332 and epithelial hemidesmosomes", "recombinant binding and adhesion/organization", "direct/proximal binding; function", "downstream_pathway_function", "LAMC2/laminin-332-alpha6beta4 hemidesmosome branch", "high", "", "reviewed_relay_candidate", "Gamma2 is a ligand-complex component; no chain-isolated binding claim.")
    add(specs, "lamb2_a3b1", ids(413), "https://pubmed.ncbi.nlm.nih.gov/16413178/; https://pubmed.ncbi.nlm.nih.gov/19147489/", "human recombinant", "laminin-521 and alpha3beta1", "binding and beta-chain comparison", "direct binding; function", "downstream_pathway_function", "LAMB2/laminin-521-alpha3beta1 branch", "medium-high", "", "reviewed_relay_candidate", "Beta2 attribution depends on full alpha5beta2gamma1 trimer.")
    add(specs, "lamb2_a6b1", ids(414), "https://pubmed.ncbi.nlm.nih.gov/16413178/; https://pubmed.ncbi.nlm.nih.gov/19147489/", "human recombinant", "laminin-521 and alpha6beta1", "binding and beta-chain comparison", "direct binding", "ligand_receptor_binding_or_activation", "LAMB2/laminin-521-alpha6beta1 branch", "high", "", "reviewed_binding_only", "Exact binding supported; no terminal TF.")
    add(specs, "lamb2_a6b4", ids(415), "https://pubmed.ncbi.nlm.nih.gov/16413178/; https://pubmed.ncbi.nlm.nih.gov/19147489/", "human recombinant", "laminin-521 and alpha6beta4", "binding and beta-chain comparison", "direct binding; proximal adhesion", "downstream_pathway_function", "LAMB2/laminin-521-alpha6beta4 branch", "medium", "", "reviewed_relay_candidate", "No matched beta4-tail functional assay.")
    add(specs, "lamb2_a7b1", ids(416), "https://pubmed.ncbi.nlm.nih.gov/16413178/; https://pubmed.ncbi.nlm.nih.gov/19147489/", "human recombinant", "alpha7 splice variants and laminin-521", "binding and splice/chain comparison", "direct binding", "ligand_receptor_binding_or_activation", "LAMB2/laminin-521-alpha7beta1 branch", "medium", "", "reviewed_binding_only", "Splice-dependent intact-laminin evidence.")

    # Netrin, NCAM, Reelin and thrombospondins.
    add(specs, "ncam1_fgfr1", ids(455), "https://pubmed.ncbi.nlm.nih.gov/12791257/; https://pmc.ncbi.nlm.nih.gov/articles/PMC2806277/", "human and mouse", "fibroblast, epithelial and neuronal models", "SPR/NMR, FGFR1 phosphorylation, Src/ERK, recycling, migration and neurite outgrowth", "direct co-receptor binding; receptor-proximal function", "downstream_pathway_function", "NCAM1-FGFR1-Src/ERK co-receptor branch", "high", "", "reviewed_relay_candidate", "NCAM is a co-receptor/adhesion molecule, not a secreted FGF ligand; no SCI-specific reuse.")
    add(specs, "ntn1_dcc", ids(457), "https://pubmed.ncbi.nlm.nih.gov/12810718/; https://pmc.ncbi.nlm.nih.gov/articles/PMC4412161/", "mouse/chick", "purified receptors and commissural axon models", "structural/stoichiometric binding and axon attraction", "direct binding; function", "downstream_pathway_function", "NTN1-DCC attractive axon-guidance branch", "high", "", "reviewed_relay_candidate", "Developmental neural context; no TF.")
    add(specs, "ntn1_dscam", ids(458), "https://pubmed.ncbi.nlm.nih.gov/19196994/; https://pubmed.ncbi.nlm.nih.gov/18585357/", "mouse/chick", "DSCAM-expressing cells and commissural axons", "cell binding, DSCAM knockdown and Fyn/PAK1", "receptor-proximal function", "downstream_pathway_function", "NTN1-DSCAM-Fyn/PAK1 axon-guidance branch", "medium", "", "reviewed_relay_candidate", "Cell-surface cofactors and species/model differences; no TF.")
    add(specs, "ntn1_unc5a", ids(459), "https://pubmed.ncbi.nlm.nih.gov/25123307/; https://pmc.ncbi.nlm.nih.gov/articles/PMC4412161/", "human/mouse structural", "UNC5A/DCC ternary receptor systems", "structure and receptor-complex switching", "receptor-complex/proximal activation", "receptor_proximal_relay", "NTN1-DCC-UNC5A repulsive ternary branch", "medium", "", "reviewed_relay_candidate", "Clean UNC5A-only functional perturbation is limited.")
    add(specs, "ntn1_unc5b", ids(460), "https://pmc.ncbi.nlm.nih.gov/articles/PMC2839190/", "human and rat", "HEK293T and rat cortical neurons", "PIKE-L/Fyn/PI3K-Akt, UNC5B depletion and Fyn-null comparison", "receptor-proximal function", "downstream_pathway_function", "NTN1-UNC5B-PIKE-L/Fyn/PI3K-AKT survival branch", "high", "", "reviewed_relay_candidate", "Functional/proximal rather than purified affinity evidence.")
    add(specs, "ntn1_unc5c", ids(461), "https://pubmed.ncbi.nlm.nih.gov/15574733/; https://pubmed.ncbi.nlm.nih.gov/21307253/", "mouse and human", "UNC5C-expressing cells and developmental axons", "cell binding, Ig2 requirement, knockout/rescue", "direct/proximal binding; function", "downstream_pathway_function", "NTN1-UNC5C repulsive axon-guidance branch", "medium", "", "reviewed_relay_candidate", "Cell-based binding and developmental context.")
    add(specs, "reln_a3b1", ids(462), "https://pubmed.ncbi.nlm.nih.gov/10939329/; https://pmc.ncbi.nlm.nih.gov/articles/PMC6673609/", "mouse", "cortical neurons and migration models", "association, migration, adhesion and genetic comparisons", "proximal association; function", "downstream_pathway_function", "RELN-alpha3beta1 cortical migration branch", "medium", "", "reviewed_relay_candidate", "Later beta1/alpha3 genetics challenge essentiality; developmental-only reuse.")
    add(specs, "thbs1_cd36", ids(463), "https://pubmed.ncbi.nlm.nih.gov/7531696/; https://pmc.ncbi.nlm.nih.gov/articles/PMC2141641/", "human and mouse", "endothelial cells and CD36 models", "fusion-protein binding, CD36 blockade/null and antiangiogenic assays", "direct binding; receptor-proximal function", "downstream_pathway_function", "THBS1-CD36 antiangiogenic endothelial branch", "high", "", "reviewed_relay_candidate", "Microvascular endothelial and receptor-state context.")
    add(specs, "thbs1_cd47", ids(464), "https://pubmed.ncbi.nlm.nih.gov/8550562/", "human", "endothelial cells", "RFYVVM affinity-labeling, anti-CD47 chemotaxis and VEGFR2/NO responses", "direct domain binding; function", "downstream_pathway_function", "THBS1-CD47 endothelial motility/NO branch", "high", "", "reviewed_relay_candidate", "C-terminal domain/peptide and CD47 context must be retained.")
    add(specs, "thbs1_a3b1", ids(465), "https://pubmed.ncbi.nlm.nih.gov/10196234/; https://doi.org/10.1074/jbc.274.34.24080", "human", "breast carcinoma/endothelial models", "TSP1 fragments, alpha3beta1 blocking and spreading/chemotaxis", "functional ligand-specific adhesion", "downstream_pathway_function", "THBS1-alpha3beta1 matrix adhesion branch", "high", "", "reviewed_relay_candidate", "No purified full-length binary assay; activated alpha3beta1/matrix context.")
    add(specs, "thbs1_avb3", ids(466), "https://pubmed.ncbi.nlm.nih.gov/2848850/; https://pubmed.ncbi.nlm.nih.gov/8896608/", "human", "endothelial, smooth-muscle and U937 cells", "RGD adhesion, alphaVbeta3 blockade and FAK phosphorylation", "functional receptor attribution", "downstream_pathway_function", "THBS1-RGD-alphaVbeta3/FAK branch", "high", "", "reviewed_relay_candidate", "Direct purified binding less isolated; RGD/Ca2+/conformation/cell-state dependent.")
    add(specs, "thbs1_sdc1", ids(467), "https://pubmed.ncbi.nlm.nih.gov/11257118/; https://pmc.ncbi.nlm.nih.gov/articles/PMC2199199/", "human and mouse", "COS-7 and C2C12", "SDC1 depletion/overexpression, glycosaminoglycan and spreading assays", "receptor-proximal glycan-mediated function", "downstream_pathway_function", "THBS1-SDC1-GAG matrix spreading branch", "medium", "", "reviewed_relay_candidate", "Likely GAG-mediated; no direct SDC1 core-protein binding.")
    add(specs, "thbs1_sdc4", ids(468), "https://pubmed.ncbi.nlm.nih.gov/17879962/", "human", "HUVEC", "TSP1 fragments/motif competition, anti-SDC4 and tubulogenesis/PKC-AKT", "receptor-proximal function", "downstream_pathway_function", "THBS1-SDC4-GAG/PKC-AKT angiogenesis branch", "medium", "", "reviewed_relay_candidate", "Fragment/motif and GAG-dependent; no clean core-protein binary binding.")
    add(specs, "thbs2_cd36", ids(469), "https://pubmed.ncbi.nlm.nih.gov/15748999/", "mouse", "CD36 fusion proteins, macrophages and corneal-pocket model", "radiolabeled binding, anti-CD36/null and antiangiogenic assay", "direct binding; function", "downstream_pathway_function", "THBS2-CD36 antiangiogenic branch", "high", "", "reviewed_relay_candidate", "Exact mouse pair; HRGP decoy-receptor context and human transfer limited.")

    assigned = {rid for s in specs for rid in s["ids"]}
    if len(assigned) != 125:
        raise SystemExit(f"expected 125 assigned outcomes, got {len(assigned)}")
    if not assigned.issubset(pair_by_review):
        raise SystemExit(f"assigned IDs absent from scaffold: {sorted(assigned - set(pair_by_review))}")

    max_reuse = max((int(r["pathway_reuse_key"].rsplit("-", 1)[1]) for r in reuse_rows if r["pathway_reuse_key"].startswith("M21A-REUSE-")), default=0)
    old_detail = read(DETAIL) if DETAIL.exists() else []
    if old_detail and "evidence_id" not in old_detail[0]:
        old_detail = []
    old_detail = [r for r in old_detail if not (r.get("evidence_id", "").startswith("M21A-PAIR-EVID-") and int(r["evidence_id"].rsplit("-", 1)[1]) >= 77)]
    max_evidence = max((int(r["evidence_id"].rsplit("-", 1)[1]) for r in old_detail if r.get("evidence_id", "").startswith("M21A-PAIR-EVID-")), default=0)
    detail_fields = ["evidence_id", "pathway_reuse_key", "source_locators", "species", "cell_type_model", "assay_or_perturbation", "relation_type", "evidence_layer", "pathway_branch", "confidence_tier", "evidence_summary", "limitations"]
    new_reuse, review_rows = [], []
    for s in specs:
        max_evidence += 1
        relay = s["status"] in {"reviewed_relay_candidate", "reviewed_function_only", "reviewed_scavenging_only"}
        if relay:
            max_reuse += 1
            reuse_key = f"M21A-REUSE-{max_reuse:04d}"
        else:
            reuse_key = ""
        evidence_id = f"M21A-PAIR-EVID-{max_evidence:03d}"
        if relay:
            new_reuse.append({"pathway_reuse_key": reuse_key, "source_entity": str(s["branch"]).split("-")[0], "pathway_name": s["branch"], "edge_ids": "", "evidence_ids": evidence_id, "target_entities": "", "ligand_pair_count": str(len(s["ids"])), "ligand_pair_keys": ";".join(sorted(pair_by_review[x]["pair_key"] for x in s["ids"])), "terminal_tf_entities": s["tf"], "validation_status": "reviewed_batch006_010_candidate", "reuse_rule": "Reuse only when exact ligand/receptor complex, isoform/chain/cofactor, species, cell/model, assay and evidence scope match.", "limitations": s["note"]})
        old_detail.append({"evidence_id": evidence_id, "pathway_reuse_key": reuse_key, "source_locators": s["locators"], "species": s["species"], "cell_type_model": s["model"], "assay_or_perturbation": s["assay"], "relation_type": s["relation"], "evidence_layer": s["layer"], "pathway_branch": s["branch"], "confidence_tier": s["confidence"], "evidence_summary": s["branch"], "limitations": s["note"]})
        for rid in s["ids"]:
            pair = pair_by_review[rid]
            pair["pathway_reuse_keys"] = reuse_key
            pair["module21a_edge_ids"] = "PENDING_M21A_EDGE_MATERIALIZATION" if relay else ""
            pair["module21a_evidence_ids"] = evidence_id
            pair["terminal_tf_entities"] = s["tf"]
            pair["module21a_status"] = s["status"]
            pair["module22a_status"] = "candidate_tf_handoff_pending_validation" if s["tf"] else "no_terminal_tf_evidence"
            pair["search_boundary"] = "primary_review_batches006_010"
            pair["curator_notes"] = s["note"]
            tfrow = tf_by_pair[pair["pair_key"]]
            tfrow["pathway_reuse_keys"] = reuse_key
            tfrow["terminal_tf_entities"] = s["tf"]
            tfrow["module21a_evidence_ids"] = evidence_id
            tfrow["handoff_status"] = "pending_tf_program_review" if s["tf"] else "no_terminal_tf_assigned"
            tfrow["terminal_tf_status"] = "candidate_or_supported_activation" if s["tf"] else "none_found"
            tfrow["search_boundary"] = "Primary downstream review batches006_010; TF target-program search remains separate."
            tfrow["limitations"] = s["note"]
            review_rows.append({"review_id": rid, "pair_key": pair["pair_key"], "pair_label_canonical": pair["pair_label_canonical"], "pathway_reuse_key": reuse_key, "evidence_id": evidence_id, "source_locators": s["locators"], "species": s["species"], "cell_type_model": s["model"], "assay_or_perturbation": s["assay"], "relation_type": s["relation"], "evidence_layer": s["layer"], "pathway_branch": s["branch"], "confidence_tier": s["confidence"], "terminal_tf_entities": s["tf"], "review_status": s["status"], "curator_note": s["note"]})

    write(PAIR, list(pair_rows[0]), pair_rows)
    write(TF, list(tf_rows[0]), tf_rows)
    write(REUSE, list(reuse_rows[0]), reuse_rows + new_reuse)
    write(DETAIL, detail_fields, old_detail)
    write(REVIEW, list(review_rows[0]), review_rows)
    print(f"integrated {len(review_rows)} pair outcomes, {len(new_reuse)} reusable pathway candidates, and {len(review_rows)} detailed evidence records")


if __name__ == "__main__":
    main()
