#!/usr/bin/env python3
"""Recover exact Plexin-B receptor-function programs from terminal-TF boundaries."""
import csv,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; EDGE_PATH=ROOT/"work/module_b_consolidation/module22b/module22b_edge_register.tsv"; EVIDENCE_PATH=ROOT/"work/module_b_consolidation/module22b/module22b_evidence_register.tsv"; AUDIT_PATH=ROOT/"work/module22b_low_confidence_upgrade_audit/module22b_low_confidence_upgrade_batch018.tsv"; SUMMARY_PATH=ROOT/"work/module22b_low_confidence_upgrade_audit/module22b_low_confidence_upgrade_batch018_summary.json"; BATCH_ID="module22b-low-confidence-upgrade-batch018-2026-09-03"
U={
"M22B-E005643":("M22B-EVID-005519","SEMA4A","SEMA4A binds PLXNB1 and supports RND1-dependent Plexin-B guidance signaling; no terminal TF-target regulation is assigned","SEMA4A-PLXNB1 -> RND1-dependent guidance program","DOI:10.3892/ijmm_00000334","human recombinant and neuronal comparator systems","Primary receptor-transfection and morphology studies support direct SEMA4A-PLXNB1 binding and RND1-dependent receptor-proximal guidance output. This recovers an exact receptor function program, but not a terminal TF or broad in vivo mechanism.","Plexin-B1 expression, membrane context, RND1 state, and neuronal model constrain transfer; no terminal TF occupancy or SCI receiver program was measured."),
"M22B-E005644":("M22B-EVID-005520","SEMA4A","SEMA4A binds PLXNB2 and supports RND1-dependent Plexin-B guidance signaling; no terminal TF-target regulation is assigned","SEMA4A-PLXNB2 -> RND1-dependent guidance program","DOI:10.3892/ijmm_00000334","human recombinant and neuronal comparator systems","Primary receptor-transfection and morphology studies directly test SEMA4A-PLXNB2 binding and a RND1-dependent engineered-cell response. This recovers an exact receptor function program, but not a terminal TF or universal physiological relay.","Plexin-B2 ligand combinations, membrane presentation, RND1 state, and limited physiological validation constrain transfer; no terminal TF occupancy or SCI receiver program was measured."),
"M22B-E005645":("M22B-EVID-005521","SEMA4A","SEMA4A binds PLXNB3 and supports RND1-dependent Plexin-B guidance signaling; no terminal TF-target regulation is assigned","SEMA4A-PLXNB3 -> RND1-dependent guidance program","DOI:10.3892/ijmm_00000334","human recombinant and neuronal comparator systems","Primary receptor-transfection and morphology studies support direct SEMA4A-PLXNB3 binding and a RND1-dependent engineered-cell response. This recovers an exact receptor function program, but not a terminal TF or broad physiological mechanism.","Plexin-B3 ligand specificity, membrane context, and limited independent physiological validation constrain transfer; no terminal TF occupancy or SCI receiver program was measured."),
"M22B-E005648":("M22B-EVID-004932","SERPINF1","PEDF binds PLXDC2, alters receptor oligomerization, and supports PLXDC2-dependent cell responses; no terminal TF-target regulation is assigned","SERPINF1/PEDF-PLXDC2 -> atypical receptor response program","PMID:25535841; PMCID:PMC4303762; DOI:10.7554/eLife.05401","mouse; human cell systems","Primary binding and cell-based studies support PEDF engagement of PLXDC2, receptor oligomerization changes, and PLXDC2-dependent cellular responses. This recovers an exact atypical-receptor function program, but not a universal kinase or terminal TF.","PLXDC2 and PLXDC1 have overlapping but distinct cellular roles and no established universal kinase/adaptor relay; no terminal TF occupancy or SCI receiver program was measured."),
}
EF=["b_edge_id","source_entity","relation_type","target_entity","pathway_name","evidence_layer","source_a_edge_id","edge_status","context_scope","cell_type_context","compartment_context","species_context","injury_context","confidence_tier","export_priority","exportable","consolidation_note"]; VF=["b_evidence_id","source_a_evidence_id","b_edge_ids","source_kind","source_locator","support_kind","species_support","source_scope","confidence_tier","citation_note","evidence_summary","limitations","evidence_layer","exportable","consolidation_note"]; AF=["batch_id","b_edge_id","b_evidence_id","old_edge_confidence","new_edge_confidence","old_evidence_confidence","new_evidence_confidence","old_target","new_target","old_edge_status","new_edge_status","decision_basis","source_locator","module22b_register_changed","canonical_sql_materialization"]
def rd(p):
 with p.open(newline="",encoding="utf-8") as h:return list(csv.DictReader(h,delimiter="\t"))
def wr(p,rows,fields):
 with p.open("w",newline="",encoding="utf-8") as h:
  w=csv.DictWriter(h,fieldnames=fields,delimiter="\t",lineterminator="\n");w.writeheader();w.writerows(rows)
def once(v,x):return v if x in v else (f"{v}; {x}" if v else x)
def main():
 edges,evidence=rd(EDGE_PATH),rd(EVIDENCE_PATH); eb={r["b_edge_id"]:r for r in edges}; vb={r["b_evidence_id"]:r for r in evidence}; audit=[]
 for eid,c in U.items():
  vid,src,rel,tgt,loc,species,basis,scope=c;e,v=eb.get(eid),vb.get(vid)
  if e is None or v is None:raise SystemExit(f"missing batch018 row for {eid}")
  if e["confidence_tier"]!="low" or e["edge_status"]!="no_evidence_boundary":raise SystemExit(f"{eid}: expected low boundary")
  if v["source_kind"]!="no_evidence_boundary" or v["support_kind"]!="negative_evidence":raise SystemExit(f"{eid}: expected boundary evidence")
  oldt,olds,olde,oldv=e["target_entity"],e["edge_status"],e["confidence_tier"],v["confidence_tier"]
  e.update({"source_entity":src,"relation_type":rel,"target_entity":tgt,"pathway_name":"cell_state_program","edge_status":"reviewed_program_association","context_scope":scope,"confidence_tier":"medium","exportable":"true"});e["consolidation_note"]=once(e["consolidation_note"],f"Low-confidence recovery batch018: medium after exact primary receptor/function re-review for {src}.")
  v.update({"source_kind":"reviewed_program_association","source_locator":loc,"support_kind":"primary_experiment","species_support":species,"source_scope":"contextual_support","confidence_tier":"high","evidence_summary":basis,"limitations":scope,"evidence_layer":"downstream_or_functional","exportable":"true"});v["consolidation_note"]=once(v["consolidation_note"],"Low-confidence recovery batch018: exact primary receptor-complex/function evidence recovered; terminal TF claim remains excluded.")
  audit.append({"batch_id":BATCH_ID,"b_edge_id":eid,"b_evidence_id":vid,"old_edge_confidence":olde,"new_edge_confidence":e["confidence_tier"],"old_evidence_confidence":oldv,"new_evidence_confidence":v["confidence_tier"],"old_target":oldt,"new_target":tgt,"old_edge_status":olds,"new_edge_status":e["edge_status"],"decision_basis":basis,"source_locator":loc,"module22b_register_changed":"true","canonical_sql_materialization":"false"})
 wr(EDGE_PATH,edges,EF);wr(EVIDENCE_PATH,evidence,VF);AUDIT_PATH.parent.mkdir(parents=True,exist_ok=True);wr(AUDIT_PATH,audit,AF);counts={"batch_id":BATCH_ID,"records_upgraded":len(audit),"medium_edge_upgrades":len(audit),"recovered_boundary_edges":len(audit),"low_edges_after":sum(r["confidence_tier"]=="low" for r in edges),"low_medium_edges_after":sum(r["confidence_tier"]=="low-medium" for r in edges),"medium_edges_after":sum(r["confidence_tier"]=="medium" for r in edges),"medium_high_edges_after":sum(r["confidence_tier"]=="medium-high" for r in edges),"high_edges_after":sum(r["confidence_tier"]=="high" for r in edges),"exportable_edges_after":sum(r["exportable"]=="true" for r in edges),"canonical_sql_materialization":False,"audit":str(AUDIT_PATH)};SUMMARY_PATH.write_text(json.dumps(counts,indent=2)+"\n",encoding="utf-8");print(json.dumps(counts,indent=2))
if __name__=="__main__":main()
