#!/usr/bin/env python3
"""Run the shared boundary-promotion routine for batch 019."""
from pathlib import Path
import promote_module22b_low_confidence_batch018 as base

base.BATCH_ID = "module22b-low-confidence-upgrade-batch019-2026-09-03"
base.AUDIT_PATH = base.ROOT / "work/module22b_low_confidence_upgrade_audit/module22b_low_confidence_upgrade_batch019.tsv"
base.SUMMARY_PATH = base.ROOT / "work/module22b_low_confidence_upgrade_audit/module22b_low_confidence_upgrade_batch019_summary.json"

def item(evidence_id, source, relation, target, locators, species, basis, scope):
    return (evidence_id, source, relation, target, locators, species, basis, scope)

base.U = {
    "M22B-E005651": item("M22B-EVID-004948", "SHH", "SHH binds or is presented by GPC1 as a heparan-sulfate coreceptor and supports an HHIP/axon-response program; no terminal TF-target regulation is assigned", "SHH-GPC1 -> Hedgehog coreceptor presentation and axon-response program", "PMID:23931997; DOI:10.1016/j.neuron.2013.05.025", "mouse; human comparator", "Primary neural studies support GPC1-dependent SHH presentation and downstream HHIP/post-crossing axon responsiveness. This recovers a bounded coreceptor function program, but not a unique intracellular relay or terminal TF.", "GPC1 is a proteoglycan presentation/coreceptor factor, and transcription-dependent versus independent axon responses differ by developmental stage; no SCI-specific terminal TF endpoint was measured."),
    "M22B-E005657": item("M22B-EVID-004862", "SEMA3B", "SEMA3B uses an NRP2/Plexin-A1 receptor complex in a neural guidance program; no terminal TF-target regulation is assigned", "SEMA3B-NRP2/PLXNA1 -> repulsive axon-guidance program", "PMID:20159958; PMID:26680304; PMCID:PMC4699389; DOI:10.1101/gad.268086.115", "mouse; human comparator", "Primary neural studies support Sema3B engagement of an NRP2/Plexin-A1 receptor complex and receptor-dependent repulsive axon-guidance output. This recovers a bounded holoreceptor function program, but not a terminal TF.", "Plexin-A1 processing/surface availability, NRP2 compartmentalization, and developmental neural context affect the output; no SCI-specific terminal TF endpoint was measured."),
    "M22B-E005666": item("M22B-EVID-005102", "TIMP2", "TIMP2 binds the alpha3beta1 integrin complex and initiates an SHP-1-dependent anti-mitogenic/anti-angiogenic relay; no terminal TF-target regulation is assigned", "TIMP2-alpha3beta1 -> integrin anti-mitogenic/anti-angiogenic program", "PMID:16326706; PMID:18721821; PMCID:PMC2574962; DOI:10.1016/j.mvr.2008.07.003; PMID:21871510; PMCID:PMC3177407; DOI:10.1016/j.peptides.2011.08.010", "human; mouse; recombinant and vascular-cell systems", "Primary studies support TIMP2 interaction with the alpha3beta1 integrin complex and SHP-1-linked anti-mitogenic or anti-angiogenic function. This recovers the complex-level program while excluding an ITGA3-only or terminal TF claim.", "The demonstrated receptor is alpha3beta1 rather than ITGA3 alone; some outputs reflect inhibition of FGF2/VEGF signaling and no terminal TF occupancy or SCI receiver program was measured."),
    "M22B-E005667": item("M22B-EVID-005103", "TIMP2", "TIMP2 signals through the beta1-containing alpha3beta1 integrin complex and supports anti-mitogenic/anti-angiogenic function; no beta1-only terminal TF edge is assigned", "TIMP2-alpha3beta1 -> beta1-containing integrin anti-mitogenic program", "PMID:16326706; PMID:18721821; PMCID:PMC2574962; DOI:10.1016/j.mvr.2008.07.003; PMID:21871510; PMCID:PMC3177407; DOI:10.1016/j.peptides.2011.08.010", "human; mouse; recombinant and vascular-cell systems", "Primary studies support TIMP2 function through the alpha3beta1 integrin complex, which contains ITGB1, with SHP-1-linked anti-mitogenic or anti-angiogenic output. This recovers the beta1-containing complex program without treating ITGB1 as an isolated receptor.", "The exact alpha partner is alpha3 in the cited receptor studies; context and FGF2/VEGF crosstalk affect output, and no terminal TF occupancy or SCI receiver program was measured."),
    "M22B-E005676": item("M22B-EVID-005190", "UCN1", "UCN1 binds and activates CRHR2alpha/beta with high-affinity cAMP-coupled signaling; no terminal TF-target regulation is assigned", "UCN1-CRHR2 -> cAMP-coupled stress-signaling program", "PMID:8612563; DOI:10.1210/endo.137.5.8612563; PMID:12611895; DOI:10.1074/jbc.M210476200; PMID:19008330", "mouse; human recombinant systems", "Primary receptor studies support UCN1 binding and activation of CRHR2 isoforms with cAMP-coupled signaling. This recovers an exact receptor function program, but not a terminal TF or universal tissue response.", "CRHR2 isoform and tissue context alter ligand affinity and output; UCN1 is not CRHR2-exclusive and no SCI-specific terminal TF endpoint was measured."),
    "M22B-E005677": item("M22B-EVID-005196", "UTS2", "UTS2 binds and activates UTS2R/GPR14 in a GPCR signaling program; no terminal TF-target regulation is assigned", "UTS2-UTS2R/GPR14 -> urotensin GPCR signaling program", "PMID:10499587; PMID:10581185; DOI:10.1038/45809; DOI:10.1006/bbrc.1999.1796", "mouse; human recombinant systems", "Primary receptor studies support the canonical UTS2-UTS2R/GPR14 ligand-receptor assignment and receptor activation. This recovers an exact GPCR function program, but not a terminal TF or universal downstream coupling.", "Downstream coupling is cell- and species-dependent and no terminal TF/transcriptional endpoint or SCI receiver result was measured."),
    "M22B-E005678": item("M22B-EVID-005198", "UTS2B", "UTS2B/URP binds and activates UTS2R/GPR14 in a GPCR signaling program; no terminal TF-target regulation is assigned", "UTS2B-UTS2R/GPR14 -> urotensin GPCR signaling program", "PMID:15476951; DOI:10.1016/j.peptides.2004.06.025", "mouse; human recombinant systems", "Primary ligand and receptor studies support UTS2B/URP binding and activation of UTS2R/GPR14. This recovers an exact GPCR function program, but not a terminal TF or universal downstream coupling.", "Ligand processing, receptor context, and cellular coupling affect output; no terminal TF/transcriptional endpoint or SCI receiver result was measured."),
    "M22B-E005680": item("M22B-EVID-005221", "VEGFA", "VEGF165 binds NRP2 and supports NRP2-dependent VEGFR-associated vascular signaling; no terminal TF-target regulation is assigned", "VEGF165-NRP2/VEGFR -> vascular/lymphatic signaling program", "PMID:10748121; PMID:20065093; DOI:10.1074/jbc.M909259199", "mouse; human recombinant systems", "Primary binding and vascular studies support VEGF165 engagement of NRP2 and NRP2-dependent VEGFR-associated responses. This recovers an isoform- and coreceptor-bounded program, but not a terminal TF.", "Binding is isoform- and heparin-dependent, NRP2 lacks an intrinsic kinase domain, and VEGFR context is required; no terminal TF occupancy or SCI receiver program was measured."),
}

if __name__ == "__main__":
    base.main()
