#!/usr/bin/env python3
"""Run the shared boundary-promotion routine for batch 020."""
import promote_module22b_low_confidence_batch018 as base

base.BATCH_ID = "module22b-low-confidence-upgrade-batch020-2026-09-03"
base.AUDIT_PATH = base.ROOT / "work/module22b_low_confidence_upgrade_audit/module22b_low_confidence_upgrade_batch020.tsv"
base.SUMMARY_PATH = base.ROOT / "work/module22b_low_confidence_upgrade_audit/module22b_low_confidence_upgrade_batch020_summary.json"

def i(*v): return v

base.U = {
    "M22B-E005649": i("M22B-EVID-004941", "SFTPD", "SFTPD engages SIRPA and supports an inhibitory alveolar-macrophage phagocytosis program; no terminal TF-target regulation is assigned", "SFTPD-SIRPA -> inhibitory macrophage function program", "PMID:18420961; DOI:10.1165/rcmb.2007-0452OC", "mouse; human comparator", "Primary collectin and macrophage studies support SFTPD engagement of SIRPA-associated inhibitory signaling and reduced phagocytic output. This recovers a bounded receptor-function program, but not a terminal TF or isolated SFTPD-only mechanism.", "The study tests SP-A and SP-D collectin context and macrophage receptor perturbations; oligomerization, collagen-domain presentation, and cell state constrain transfer, and no SCI-specific terminal TF endpoint was measured."),
    "M22B-E005650": i("M22B-EVID-004946", "SHBG", "SHBG engages GPRC6A and produces receptor-dependent endocrine secretion responses; no terminal TF-target regulation is assigned", "SHBG-GPRC6A -> endocrine secretion signaling program", "PMID:27673554; PMID:31857654; PMCID:PMC6923452", "mouse; human recombinant and endocrine-cell systems", "Primary receptor and endocrine studies support SHBG/GPRC6A engagement and receptor-dependent secretion responses. This recovers a bounded receptor program, but not a universal full-length SHBG mechanism or terminal TF.", "One study uses an SHBG domain peptide rather than full-length native SHBG; receptor specificity, cell model, and endocrine context constrain transfer, and no terminal TF endpoint was measured."),
    "M22B-E005652": i("M22B-EVID-004939", "SFTPD", "SFTPD binds LAIR1 and suppresses an Fc-alpha-receptor inflammatory response; no terminal TF-target regulation is assigned", "SFTPD-LAIR1 -> inhibitory myeloid inflammatory program", "PMID:24585933", "human in vitro", "Primary immune studies support SFTPD interaction with LAIR1 and suppression of an Fc-alpha-receptor inflammatory response. This recovers an exact receptor-proximal function program, but not a terminal TF.", "The evidence uses multimeric/domain-defined SFTPD and an Fc-alpha-receptor assay rather than a standalone LAIR1 pathway; no SCI receiver or terminal TF occupancy was measured."),
    "M22B-E005679": i("M22B-EVID-005227", "VEGFB", "VEGF-B isoforms bind NRP1 and support an NRP1-dependent vascular/neuronal program; no terminal TF-target regulation is assigned", "VEGF-B-NRP1 -> coreceptor-dependent vascular/neuronal program", "DOI:10.1074/jbc.274.30.21217; PMID:26483474", "human; zebrafish comparator", "Primary biochemical and developmental studies support VEGF-B/NRP1 binding and NRP1-dependent vascular or neuronal function. This recovers an isoform-bounded coreceptor program, but not a terminal TF.", "VEGF-B splice/proteolytic processing controls NRP1 binding, NRP1 lacks an intrinsic kinase domain, and developmental species/context limit transfer; no terminal TF endpoint was measured."),
    "M22B-E005685": i("M22B-EVID-005238", "VIP", "VIP binds and activates PAC1/ADCYAP1R1 in a GPCR signaling program; no terminal TF-target regulation is assigned", "VIP-PAC1/ADCYAP1R1 -> cAMP-coupled neuropeptide signaling program", "PMID:9224822", "rat; recombinant receptor systems", "Primary receptor studies support VIP binding and activation of PAC1/ADCYAP1R1 with receptor-dependent second-messenger output. This recovers an exact GPCR function program, but not a terminal TF.", "PAC1 splice and receptor context affect VIP potency and coupling; no terminal transcriptional endpoint or SCI receiver result was measured."),
    "M22B-E005686": i("M22B-EVID-005253", "VIP", "VIP binds and activates VPAC1/VIPR1 in a GPCR signaling program; no terminal TF-target regulation is assigned", "VIP-VPAC1/VIPR1 -> cAMP-coupled neuropeptide signaling program", "PMID:8390245; PMID:7917790; DOI:10.1006/bbrc.1993.1658", "human; rat; recombinant receptor systems", "Primary receptor-cloning and functional studies support VIP binding and activation of VPAC1/VIPR1 with receptor-dependent signaling. This recovers an exact GPCR function program, but not a terminal TF.", "Receptor clones and nomenclature were established in heterologous systems and peptide cross-reactivity is expected; no terminal TF endpoint or SCI receiver result was measured."),
}

if __name__ == "__main__":
    base.main()
